defaults:
  - filepaths: filepaths
  - _self_

tani_filter:
  _target_: minedatabase.filters.SimilaritySamplingFilter
  sample_size: 1000
  weight: null

coreactants: metacyc_coreactants
rules: rc_plus_4_rules_w_coreactants
starters: alpha_ketoglutarate
targets: alpha_ketoglutarate_semialdehyde
a_plus_b: True
do_tani_sample: False
prune_to_targets: True
generations: 1
processes: 1 # TODO: inherit from slurm config / sh file

hydra:
  run:
    dir: ${filepaths.raw_expansions}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.raw_expansions}
    subdir: .