defaults:
  - filepaths: filepaths
  - _self_

tani_filter:
  _target_: minedatabase.filters.SimilaritySamplingFilter
  sample_size: 1000
  weight: null

coreactants: metacyc_coreactants
rules: mechinferred_dt_98_rules_w_coreactants
starters: alpha_ketoglutarate
targets: L-glutamine
a_plus_b: False
do_tani_sample: False
prune_to_targets: True
generations: 2
processes: 10

hydra:
  run:
    dir: ${filepaths.raw_expansions}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.raw_expansions}
    subdir: .