defaults:
  - filepaths: filepaths
  - _self_

tani_filter:
  _target_: minedatabase.filters.SimilaritySamplingFilter
  sample_size: 1000
  weight: null

coreactants: metacyc_coreactants
rules: mechinferred_dt_13_rules_w_coreactants
starters: hopa
targets: alpha_ketoglutarate
a_plus_b: False
do_tani_sample: False
prune_to_targets: False
generations: 1
processes: 10
retro: True

hydra:
  output_subdir: .expand
  run:
    dir: ${filepaths.raw_data}/expansions/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: ${filepaths.raw_data}/expansions/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: .