#!/bin/bash

stored_dir=241118_bottle_checkin
proc_path=/home/stef/bottle/scripts/process_expansion.py
poetry run python $proc_path $stored_dir -f 2_steps_alpha_ketoglutarate_to_None_rules_JN3604IMT_rules_carbonyl_free_co_metacyc_coreactants_carbonyl_free_sampled_False_pruned_False -r 2_steps_bottle_targets_24_to_None_rules_JN3604IMT_rules_carbonyl_free_co_metacyc_coreactants_carbonyl_free_sampled_False_pruned_False --do-thermo
poetry run python $proc_path $stored_dir -f 2_steps_amino_acids_to_None_rules_JN3604IMT_rules_co_metacyc_coreactants_sampled_False_pruned_False -r 2_steps_bottle_targets_24_to_None_rules_JN3604IMT_rules_co_metacyc_coreactants_sampled_False_pruned_False --do-thermo