source_names:
- H2O
- CoA
- ATP
- NADP(+)
- NADPH
- NAD(+)
- NADH
- phosphate
- ADP
- diphosphate
- O2
- UDP
- S-adenosyl-L-methionine
- S-adenosyl-L-homocysteine
- CO2
- UDP-alpha-D-glucose
- AMP
- acetyl-CoA
- NH4(+)
- H2O2
- hydrogen sulfide
- methane
