/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.0-linux-x64/python_files/deactivate/bash/envVars.txt
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/deactivate/bash/envVars.txt
/usr/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.8.1-linux-x64/python_files/deactivate/bash/envVars.txt
 /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 47521 -- /home/stef/bottle/scripts/download_rhea_smi_name_pairs.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 40007 -- /home/stef/bottle/scripts/download_rhea_smi_name_pairs.py  
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/deactivate/bash/envVars.txt
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/deactivate/bash/envVars.txt
/bin/python3 /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/printEnvVariablesToFile.py /home/stef/.vscode-server/extensions/ms-python.python-2025.10.0-linux-x64/python_files/deactivate/bash/envVars.txt
 /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 48333 -- /home/stef/bottle/scripts/mechanism_processing.py  
voila notebooks/path_viewer.ipynb 
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 54549 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 37933 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 37563 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 44495 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 39489 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 41865 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 36735 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 35121 -- /home/stef/bottle/scripts/mechanism_processing.py  
 cd /home/stef/bottle ; /usr/bin/env /home/stef/.cache/pypoetry/virtualenvs/bottle-bcOlvnza-py3.12/bin/python /home/stef/.vscode-server/extensions/ms-python.debugpy-2025.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 36559 -- /home/stef/bottle/scripts/mechanism_processing.py  
